# Generated by Django 4.0 on 2021-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('address', models.CharField(blank=True, max_length=63, null=True)),
                ('study', models.CharField(blank=True, max_length=63, null=True)),
                ('degree', models.CharField(blank=True, max_length=63, null=True)),
                ('mail', models.EmailField(blank=True, max_length=63, null=True)),
                ('phone', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
