# Generated by Django 4.0 on 2022-02-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
