# Generated by Django 4.0 on 2022-02-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
