# Generated by Django 4.0 on 2022-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_blog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
