# Generated by Django 4.0 on 2022-02-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='blog/')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
