# Generated by Django 4.0 on 2022-02-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_testimonials_alter_projects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
