# Generated by Django 4.0 on 2022-02-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_testimonials_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
